#! /bin/bash

rm results.txt
touch results.txt

# Scale regularizer 0.025, noise location 0.0, noise scale 0.8, ppf-min 0.0, ppf-max 0.9, relocation opacity
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 3 >> results.txt

# Scale regularizer 0.025, noise location 0.0, noise scale 0.8, ppf-min 0.0, ppf-max 0.9, relocation l1
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type l1 --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type l1 --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type l1 --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.025 --scale-reg-type vol --noise-distribution levy --relocation-type l1 --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.0 --ppf-max-range 0.9 --test-every 4 --test-every-offset 3 >> results.txt

# Scale regularizer 0.025, noise location 0.0, noise scale 0.8, ppf-min 0.0, ppf-max 0.9, relocation l1
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale-reg 0.01 --scale-reg-type mean --noise-distribution gaussian --relocation-type l1 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale-reg 0.01 --scale-reg-type mean --noise-distribution gaussian --relocation-type l1 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale-reg 0.01 --scale-reg-type mean --noise-distribution gaussian --relocation-type l1 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale-reg 0.01 --scale-reg-type mean --noise-distribution gaussian --relocation-type l1 --test-every 4 --test-every-offset 3 >> results.txt

