#! /bin/bash

rm results.txt
touch results.txt

# Noise location 0.0, Noise scale 0.8, PPF range 0.2 - 1.0
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 3 >> results.txt

# Noise location 0.0, Noise scale 0.9, PPF range 0.2 - 1.0
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.0 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 3 >> results.txt

# Noise location 0.1, Noise scale 0.8, PPF range 0.2 - 1.0
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.8 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 3 >> results.txt

# Noise location 0.1, Noise scale 0.9, PPF range 0.2 - 1.0
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 0 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 1 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 2 >> results.txt
CUDA_VISIBLE_DEVICES=0 python examples/custom_trainer.py custom --data-dir examples/data/360_v2/counter/ --data-factor 4 --result-dir ./examples/results/counter/ --init-type random --scale_reg 0.01 --scale-reg-type mean --noise-distribution levy --relocation-type opacity --noise-location 0.1 --noise-scale 0.9 --ppf-min-range 0.2 --ppf-max-range 1.0 --test-every 4 --test-every-offset 3 >> results.txt


